commerce_tahseel_gateway.commerce_payment_gateway.plugin.quickpay_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    national_id:
      type: string
      label: 'National ID'
    iqama_id:
      type: string
      label: 'Iqama ID'

