commerce_payment.commerce_payment_gateway.plugin.tahseel:
  type: commerce_payment_gateway_configuration
  mapping:
    nationalid:
      type: text
      label: 'National ID'
      translatable: true
    residentid:
      type: text
      label: 'Resident ID'
      translatable: true
